### ISSUE TITLE
disk リソースで hostname パラメーターが未実装

### ISSUE THREAD

**Issue by tmy** [yamamoto-febc/terraform-provider-sakuracloud#51]
https://github.com/yamamoto-febc/terraform-provider-sakuracloud/blob/master/builtin/providers/sakuracloud/resource_sakuracloud_disk.go#L87 を見ると、定義がコメントアウトされているようですが、これは何か事情があるのでしょうか？

**Comment by yamamoto-febc** [comment]
サーバーリソースに定義するか、ディスクリソースに定義するか迷った時の名残ですね。。。
コメント解除すべき項目だと思います。
近いうちに直しますね。

**Comment by yamamoto-febc** [comment]
@tmy  #52 をマージしたバージョンをリリースしました。

https://github.com/yamamoto-febc/terraform-provider-sakuracloud/releases/tag/v0.4.3

一度お試しください。コントリビューションありがとうございました!!
