### ISSUE TITLE
importしたサーバーのipが変わらない

### ISSUE THREAD

**Issue by kazuminn** [yamamoto-febc/terraform-provider-sakuracloud#53]
こんにちは
質問です。

terraform 0.7.1
plugin 最新

terraform importしたサーバのipを以下のようにして変更することはできないのでしょうか？
試しましたが、失敗しました。

resource "sakuracloud_server" "004" {
    name = "004"
    disks = ["${sakuracloud_disk.disk4.id}"]
    base_interface = "112700593"
    base_nw_ipaddress = "ipv6"
}       

クラウド側で手動で作ったサーバーがあったので、terraform importしました。
以下のように初期値が入っていました。

<pre>
additional_interfaces.# = 0
  base_interface = 112700616593
  base_nw_address = 153.120.161.112
  base_nw_dns_servers.# = 2
  base_nw_dns_servers.0 = 133.242.0.3
  base_nw_dns_servers.1 = 133.242.0.4
  base_nw_gateway = 153.120.161.113
  base_nw_ipaddress = 
  base_nw_mask_len = 28
</pre>

**Comment by yamamoto-febc** [comment]
`base_nw_ipaddress`でのIPアドレス指定は、サーバーのNICがどこにつながっているかによって
設定可否が決まります。

#### 共有セグメントにつながっている場合

この場合 `base_nw_address`は設定できません。
さくらのクラウド側からグローバルIPが一つ割り当てられます。

#### スイッチ + ルーターにつながっている場合

接続されているルーターが持つグローバルIPの範囲であれば `base_nw_address`に設定可能です。

#### スイッチにつながっている場合

任意のIPアドレスを `base_nw_address`に設定可能です。

**Comment by kazuminn** [comment]
今回は、スイッチ + ルーターにつながっている場合です。

"接続されているルーターが持つ"というのがあまりわかりません。
ipv6を割り当てたいのです。
"持つ"というのは、該当スイッチのipv6逆引き登録されているものでしょうか？

**Comment by kazuminn** [comment]
ルーターのIPv6割当可能範囲のことでしょうか？
その範囲なのですが、変更できませんでした。

**Comment by yamamoto-febc** [comment]
まずIPv4での話になるのですが、
スイッチ + ルーターとはグローバルIPアドレスをサブネット単位で確保するものです。
"接続されているルーターが持つ"というのはスイッチ + ルーターが確保したグローバルIPです。
`terraform import`の結果を見ると、`153.120.161.112/28`が割り当てられているようですね。

この範囲からネットワークアドレスに1個、ブロードキャストアドレスに1個、ゲートウェイアドレスに3個(ゲートウェイアドレスのIPアドレス1個に加え、冗長化のため内部的に2個のIPアドレスを使用)の計5個を除いたグローバルIPがサーバーに割り当て可能なものです。

**Comment by kazuminn** [comment]
なるほど。

**Comment by yamamoto-febc** [comment]
そしてIPv6ですが、現在サポートできておりません。。。

というのも、サーバーへのIPアドレスの設定には[ディスクの修正](https://help.sakura.ad.jp/app/answers/detail/a_id/2604/~/ディスク修正)というさくらのクラウドAPIを利用しているのですが、こちらがIPv6非対応となっております。

**Comment by kazuminn** [comment]
わかりました。
ありがとうございます！

**Comment by yamamoto-febc** [comment]
ご質問ありがとうございました！
IPv6サポートされ次第`Terraform for さくらのクラウド`へ機能追加しますね！

**Comment by kazuminn** [comment]
++1

**Comment by kazuminn** [comment]
terraform importして、初めてapplyするときは、ip_nw_addressの設定はできました。
しかし、その後にその値を変更しても反映されません。これは仕様ですか？

**Comment by yamamoto-febc** [comment]
変わるのが正しいはずです。
`import`コマンドとは関連しない問題に見えるため、別途Issue立てましょう。
