### ISSUE TITLE
サーバーリソースでのIPアドレスの変更ができない

### ISSUE THREAD

**Issue by yamamoto-febc** [yamamoto-febc/terraform-provider-sakuracloud#54]
From #53 

変更前
```
resource "sakuracloud_server" "foobar" {
    name = "test"
    disks = ["${sakuracloud_disk.foobar.id}"]
    base_interface = "${sakuracloud_switch.sw01.id}"
    base_nw_mask_len = "24"
    base_nw_gateway = "192.168.100.1"
    base_nw_ipaddress = "192.168.100.101"
}
```

変更後

```
resource "sakuracloud_server" "foobar" {
    name = "test"
    disks = ["${sakuracloud_disk.foobar.id}"]
    base_interface = "${sakuracloud_switch.sw01.id}"
    base_nw_mask_len = "24"
    base_nw_gateway = "192.168.100.1"
    base_nw_ipaddress = "192.168.100.102"
}

```

変更後に`terraform plan`実行

```
$ terraform plan
~ sakuracloud_server.foobar
    base_nw_gateway:   "" => "192.168.100.1"
    base_nw_ipaddress: "192.168.100.101" => "192.168.100.102"
    base_nw_mask_len:  "" => "24"
```

この状態で`terraform apply`しても反映されない

**Comment by yamamoto-febc** [comment]
@kazummin 修正版をリリースしました。
https://github.com/yamamoto-febc/terraform-provider-sakuracloud/releases/tag/v0.4.4
問題がある場合はこのIssueを再オープンしてください。

コントリビューションありがとうございました！

**Comment by kazuminn** [comment]
問題が、ありました。
私に再open権限がないので、代わりに再openしてください。

# 問題
上のip環境で説明します。
実際にサーバを見てみると、
192.168.100.102がeth0のセカンダリアドレスに追加されています。
できれば、プライマリの方を変更したいです。

**Comment by yamamoto-febc** [comment]
ご報告ありがとうございます！
再現確認してみますので少々お待ちください。

**Comment by yamamoto-febc** [comment]
@kazuminn こちらの環境/手順では再現しないようです。

### 確認手順

  - 1) `terraform apply`でサーバー + ディスク作成
  - 2) tfファイルでIPアドレスを変更し`terraform apply`再実行

ちょっと長いですが、以下がtfファイルです。

#### 1) IPアドレス変更前のtfファイル

```
provider sakuracloud {
    zone = "is1b"
}
data "sakuracloud_archive" "centos" {
    filter = {
        name   = "Tags"
        values = ["current-stable", "arch-64bit", "distro-centos"]
    }
}
resource "sakuracloud_disk" "foobar" {
    name = "mydisk"
    source_archive_id = "${data.sakuracloud_archive.centos.id}"
    hostname = "testhost"
    password = "xxxxxxxx"
}
resource "sakuracloud_switch" "sw01" {
   name = "sw01"
}

resource "sakuracloud_server" "foobar" {
    name = "name_test"
    disks = ["${sakuracloud_disk.foobar.id}"]
    base_interface = "${sakuracloud_switch.sw01.id}"
    base_nw_ipaddress = "192.168.100.101"
    base_nw_mask_len = "24"
    base_nw_gateway = "192.168.100.1"
}
```

#### 2) IPアドレス変更後のtfファイル

```
provider sakuracloud {
    zone = "is1b"
}
data "sakuracloud_archive" "centos" {
    filter = {
        name   = "Tags"
        values = ["current-stable", "arch-64bit", "distro-centos"]
    }
}
resource "sakuracloud_disk" "foobar" {
    name = "mydisk"
    source_archive_id = "${data.sakuracloud_archive.centos.id}"
    hostname = "testhost"
    password = "xxxxxxxx"
}
resource "sakuracloud_switch" "sw01" {
   name = "sw01"
}

resource "sakuracloud_server" "foobar" {
    name = "name_test"
    disks = ["${sakuracloud_disk.foobar.id}"]
    base_interface = "${sakuracloud_switch.sw01.id}"
    base_nw_ipaddress = "192.168.100.102"
    base_nw_mask_len = "24"
    base_nw_gateway = "192.168.100.1"
}
```

そちらとの環境の違い(インストールするOSなど)などがもしあれば情報ください。
また、セカンダリIPが登録された状態での`ip`コマンド(`ip addr show`など)の結果、NIC定義ファイル(`/etc/sysconfig/network-script/ifcfg-eth0`など)についても提示いただけると助かります。

**Comment by kazuminn** [comment]
# OS
<pre>
data sakuracloud_archive "centos" {
    filter = { 
        name   = "Tags"
        values = ["current-stable", "arch-64bit", "distro-centos"]
    }   
}
</pre>

# ip a
<pre>
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 9c:a3:ba:30:d4:13 brd ff:ff:ff:ff:ff:ff
    inet 153.120.161.117/28 brd 153.120.161.127 scope global eth0
       valid_lft forever preferred_lft forever
    inet 153.120.161.127/28 brd 153.120.161.127 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 2401:2500:10a:1011::17/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::9ea3:baff:fe30:d413/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 9c:a3:ba:30:58:c3 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::9ea3:baff:fe30:58c3/64 scope link 
       valid_lft forever preferred_lft forever
</pre>

# /etc/sysconfig/network-scripts/ifcfg-eth0
<pre>
BOOTPROTO=static
DEVICE=eth0
DNS2=133.242.0.4
ONBOOT=yes
DNS1=133.242.0.3
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=no
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
NAME="System eth0"
UUID=5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03
IPV6ADDR=2401:2500:10a:1011::17/128
IPV6_DEFAULTGW=fe80::1
IPADDR=153.120.161.117
PREFIX=28
GATEWAY=153.120.161.113
DNS3=2001:4860:4860::8888
GATEWAY0=153.120.161.113
PREFIX0=28
IPADDR0=153.120.161.127
</pre>

**Comment by yamamoto-febc** [comment]
サーバー構築手順の確認ですが、提示いただいた情報から推測すると

  - 1) 上流をルーター(IPv6有効)に接続したサーバーを作成(またはインポート)
  - 2) 手動で`/etc/sysconfig/network-scripts/ifcfg-eth0`にIPv6関連の設定を追記
  - 3) terraformにてIPv4アドレスの変更

という流れでしょうか？

**Comment by kazuminn** [comment]
1,3,2です。

**Comment by yamamoto-febc** [comment]
やはりこちらでの再現ができないですね。
1,3,2それぞれの段階時点のtfファイル、手動で行った変更があればその内容はわかりますか？

**Comment by kazuminn** [comment]
1,,4,2,3ですね。
4と3でbase_nw_ipaddressの値を変更しています。
あ、2は手動ではありません。

このような感じで、provisioningしてます。
<pre>
resource "null_resource" "014" {
    connection {
       user = "root"
       host = "${sakuracloud_server.014.base_nw_ipaddress}"
       private_key = "${file("./id_rsa")}"
    }   

    provisioner "remote-exec" {
        inline = [ 
        ¦   "yum -y update",
        ¦   "nmcli connection modify 'System eth0' ipv6.method 'auto'",
        ¦   "nmcli connection modify 'System eth0' ipv6.addresses '2401:2500:10a:1011::25'",
        ¦   "nmcli connection modify 'System eth0' ipv6.gateway 'fe80::1'",
        ¦   "nmcli connection modify 'System eth0' ipv6.dns '2001:4860:4860::8888'",
        ¦   "nmcli connection modify 'System eth0' ipv6.method 'manual'",
        ¦   "systemctl restart NetworkManager",
        ¦   "systemctl restart network",
        ¦   "useradd ie-user",
        ¦   "mkdir /home/ie-user/.ssh/",
        ¦   "chmod 700 /home/ie-user/.ssh",
        ¦   "chmod 600 /home/ie-user/.ssh/authorized_keys",
        ¦   "sed -ie 's/^#PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config",
        ¦   "sed -ie 's/^PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config",
        ¦   "echo 'ie-user:V-S|(5cGq/Wj' | chpasswd",
        ¦   "usermod -G wheel ie-user",
        ]   
   }   

    provisioner "file" {
        ¦source = "./id_rsa.pub"
        ¦destination = "/home/ie-user/.ssh/authorized_keys"
    }   

    provisioner "remote-exec" {
        inline = [ 
        ¦   "chown -R ie-user:ie-user /home/ie-user/.ssh/",
        ¦   "chmod 600 /home/ie-user/.ssh/authorized_keys",
        ¦   "systemctl reload sshd"
        ]   
   }   
}          
</pre>

**Comment by kazuminn** [comment]
1,,4,2,3ですね。
3,4でbase_nw_ipaddressの値を変更しました。

2は、手動ではなくて以下のようにprovisioningしました。
<pre>
resource "null_resource" "014" {
    connection {
       user = "root"
       host = "${sakuracloud_server.014.base_nw_ipaddress}"
       private_key = "${file("./id_rsa")}"
    }

    provisioner "remote-exec" {
        inline = [
            "yum -y update",
            "nmcli connection modify 'System eth0' ipv6.method 'auto'",
            "nmcli connection modify 'System eth0' ipv6.addresses '2401:2500:10a:1011::25'",
            "nmcli connection modify 'System eth0' ipv6.gateway 'fe80::1'",
            "nmcli connection modify 'System eth0' ipv6.dns '2001:4860:4860::8888'",
            "nmcli connection modify 'System eth0' ipv6.method 'manual'",
            "systemctl restart NetworkManager",
            "systemctl restart network",
            "useradd ie-user",
            "mkdir /home/ie-user/.ssh/",
            "chmod 700 /home/ie-user/.ssh",
            "chmod 600 /home/ie-user/.ssh/authorized_keys",
            "sed -ie 's/^#PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config",
            "sed -ie 's/^PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config",
            "echo 'ie-user:******' | chpasswd",
            "usermod -G wheel ie-user",
        ]
   }

    provisioner "file" {
         source = "./id_rsa.pub"
         destination = "/home/ie-user/.ssh/authorized_keys"
    }

    provisioner "remote-exec" {
        inline = [
            "chown -R ie-user:ie-user /home/ie-user/.ssh/",
            "chmod 600 /home/ie-user/.ssh/authorized_keys",
            "systemctl reload sshd"
        ]
   }
}
</pre>

**Comment by yamamoto-febc** [comment]
OK、ちょっと整理しましょう。

- 1) サーバー等のクラウド上のリソースを作成
- 2) tfファイル内の`base_nw_ipaddress`を変更し`terraform apply`
- 3) null_resourceを用いたプロビジョニングを追記して`terraform apply`
- 4) 再度tfファイル内の`base_nw_ipaddress`を変更し`terraform apply`
- ** この時点でeth0にセカンダリIPが割り当てられる**


この手順で良いですか？

**Comment by kazuminn** [comment]
OKです。

**Comment by yamamoto-febc** [comment]
では一度再現できるか試してみますね。

**Comment by yamamoto-febc** [comment]
再現できました。
が、4)の手順をコントロールパネルからのIPアドレスの変更に変えても再現できましたので、
Terraform固有の問題ではなさそうです。

もう少しミニマムに再現する環境を探してみますね。

**Comment by yamamoto-febc** [comment]
原因が判明しました。
原因はNetworkManagerによる`/etc/sysconfig/network-scripts/ifcfg-eth0`の書き換えです。

以下再現作業順に解説します。
なお、以下では`/etc/sysconfig/network-scripts/ifcfg-eth0`を`NIC設定ファイル`と記します
CentOSでの例ですが他のOSでも同様だと思われます。

#### 1) サーバー作成直後のNIC設定ファイル(関係箇所抜粋)

```
GATEWAY0=153.120.97.177
PREFIX0=28
IPADDR0=153.120.97.190
```

各項目名の後ろに`0`が付いています。(IPエイリアス)

####  2) `nmcli`での設定変更後(関係箇所抜粋)

```
GATEWAY=153.120.97.177
PREFIX=28
IPADDR=153.120.97.190
```

NetworkManagerによるNIC設定ファイルの書き換えの結果、各項目名の後ろの`0`が消えました。

#### 3) TerraformからIPアドレスを変更( or コンパネから「ディスクの修正」実行)

```
GATEWAY=153.120.97.177
PREFIX=28
IPADDR=153.120.97.190

GATEWAY0=153.120.97.177 
PREFIX0=28
IPADDR0=153.120.97.191
```

#### 3)の挙動の解説

TerraformからのIPアドレス変更もコントロールパネルでの操作時も、
IPアドレス変更時には以下の「ディスクの修正」APIを利用しています。

[`PUT /disk/:diskid/config`](http://developer.sakura.ad.jp/cloud/api/1.1/disk/#put_disk_diskid_config)

このAPIでIPアドレスの変更を行った場合、以下の項目の追加 or 書き換えが行われるようです。

  - `GATEWAY0`
  - `PREFIX0`
  - `IPADDR0`

項目がなければ追加、あれば書き換えという挙動でした。

今回は2)の時点でこれらの項目がなくなった(後ろの0が消えた)ため、
3)で新たに設定が書き加えられた結果、IPアドレスを2つ持つ状態となっていました。

なお、この状態からさらにTerraform or コントロールパネルからIPアドレスを変更すると
以下のようになります。

```
GATEWAY=153.120.97.177
PREFIX=28
IPADDR=153.120.97.190

GATEWAY0=153.120.97.177
PREFIX0=28
IPADDR0=153.120.97.192    # IPADDR0だけ書き換えが行われる
```

**Comment by kazuminn** [comment]
なるほど。

では、NetworkManager介さないで、NIC設定ファイルを変更すれば良いのですね:)

**Comment by yamamoto-febc** [comment]
そうですね。`nmcli`が意図せず設定を書き換えてしまっているため、`nmcli`を利用しないようにすればこの問題の回避はできるかと思われます。
IPv6関連の設定を`/etc/sysconfig/network-scripts/ifcfg-eth0`に直接追記する方法などを一度お試しください。

**Comment by yamamoto-febc** [comment]
FYI : この現象は現時点ではCentOS7でのみ発生するようです。CentOS6では再現しませんでした。

@kazuminn 当Issueはクローズとします。何かあれば別途Issueください。
コントリビューションありがとうございました！
