### ISSUE TITLE
diskのパスワードが変更されない

### ISSUE THREAD

**Issue by kazuminn** [yamamoto-febc/terraform-provider-sakuracloud#56]
sakuracloud_diskのパスワードを変更しても変更されません。
これは仕様でしょうか？

terraform.tfstateのpasswordは変更後のパスワードに変更されています。

しかし、実際にサーバのrootのパスワードが変更されません。

**Comment by yamamoto-febc** [comment]
@kazuminn ご報告ありがとうございます！

修正版をmasterへマージしています。次回リリースまでひとまず以下NightlyBuildをお試しください。

https://github.com/yamamoto-febc/terraform-provider-sakuracloud/releases/tag/nightly

問題があれば当Issueを再オープンしてください。

コントリビューションありがとうございました！
