### ISSUE TITLE
datasourceを追加できない

### ISSUE THREAD

**Issue by kazuminn** [yamamoto-febc/terraform-provider-sakuracloud#60]
すみません。質問です。
fedora24を使いたかったので、以下のようにしたのですが、怒られました。
どのようにすればいいでしょうか？

<pre>
data sakuracloud_archive "fedora" {
    filter = { 
        name   = "Tags"
        values = ["arch-64bit","current-stable","distro-fedora","distro-ver-24","os-linux"]
    }   
}
</pre>

<pre>
* Resource 'data.sakuracloud_archive.fedora' does not have attribute 'id' for variable 'data.sakuracloud_archive.iii.id'
</pre>

**Comment by yamamoto-febc** [comment]
後ろの方に`data.sakuracloud_archive.iii.id`と出ているのですが、
これはtfファイルはどのように書かれてますか？？

**Comment by yamamoto-febc** [comment]
こちらでも調べてみました。
表示されているエラーは、`data`で指定したアーカイブが見つからなかったことによるものです。

fedoraについてですが、[パブリックアーカイブ](http://cloud-news.sakura.ad.jp/public_archive_iso/)にはfedoraは存在しないです。
ということで、さくらのクラウド上でfedoraを使うにはISOイメージからインストールする必要があります。

以下のようなtfファイルでfedoraのISOイメージを挿入した状態のサーバーが作成されます。

```tf
# dataリソースでISOイメージを検索
data sakuracloud_cdrom "fedora" {
    filter = { 
        name   = "Tags"
        values = ["arch-64bit","current-stable","distro-fedora","distro-ver-24","os-linux"]
    }   
}

# ブランクディスク
resource "sakuracloud_disk" "disk01" {
    name = "mydisk"
}

# ブランクディスク + ISOイメージを挿入したサーバー
resource "sakuracloud_server" "server01"{
    name = "server01"
    disks = ["${sakuracloud_disk.disk01.id}"]

    # ISOイメージのIDを指定
    cdrom_id = "${data.sakuracloud_cdrom.fedora.id}"
}
```

他の方法としては、あらかじめISOイメージからfedoraをインストールしたサーバーを作成し、そのディスクからアーカイブを作成、Terraformからは作成したアーカイブをdataリソースで利用するという方法もあります。

**Comment by kazuminn** [comment]
その他の方法をしたいです。

terraformから作成したアーカイブをdataリソースで利用するために、terraformをどのように書けば良いですか？

**Comment by yamamoto-febc** [comment]
まず、現状ではアーカイブを作成するところまでは手動で行う必要があります。
以下の記事などを参考に作成ください。

[さくらのクラウドニュース:TIPS アーカイブ機能を利用してみよう](http://cloud-news.sakura.ad.jp/2015/07/07/tips_archive/)

アーカイブ作成後、そのアーカイブを利用するdataリソースをtfファイルで以下のように定義します。
（アーカイブの名前で検索する例）
```
data sakuracloud_archive "fedora" {
    filter = { 
        name   = "Name"
        values = ["アーカイブ作成時に入力したアーカイブ名"]
    }   
}
resource "sakuracloud_disk" "disk01" {
    name = "disk01"
    source_archive_id = "${data.sakuracloud_archive.fedora.id}"
    # パスワードや公開鍵設定など
}
resource "sakuracloud_server" "server01"{
    name = "server01"
    disks = ["${sakuracloud_disk.disk01.id}"]
}
```

**Comment by kazuminn** [comment]
それを実行しました。
う、これってもしかして、ディスク修正に対応していないのでしょうか？
osを指定する方法あります？

<pre>
* sakuracloud_disk.disk34: Error editting SakuraCloud DiskConfig: Error in response: &sacloud.ResultErrorValue{IsFatal:true, Serial:"2dd647b16ff38a466220c94364785e3a", Status:"503 Service Unavailable", ErrorCode:"unknown_os_type", ErrorMessage:"サービスが利用できません。ディスクにインストールされたOSが特定できないため、正しく修正できません。"}
</pre>

**Comment by yamamoto-febc** [comment]
なるほど。。OSを指定する機能はないです。

現状はディスクの修正に非対応のOSに対してディスクの修正を行った場合に
エラーとしていますので、カスタムOSの場合だと対応できないですね。。

ソースにしたアーカイブによってディスクの修正を行う/行わないを切り替えれるようにすれば
いいかもしれないですね。

**Comment by yamamoto-febc** [comment]
現状では具体的な対応スケジュールは決めていないですが、
次のバージョンアップ時に検討しますので、当Issueはしばらくオープンにしておいてください。

**Comment by yamamoto-febc** [comment]
@kazuminn [Terraform for さくらのクラウド v0.5.0](https://github.com/yamamoto-febc/terraform-provider-sakuracloud/releases/tag/v0.5.0)にて対応を行いました。

ディスクの修正に非対応のOSであるかの判定を追加しています。

ディスクの修正に非対応の場合、当該機能によって設定される、以下のような項目はtfファイルで設定しても無視されます。
  - ホスト名
  - パスワード
  - IPアドレス/ゲートウェイ
  - スタートアップスクリプト
  - SSH公開鍵

是非v0.5.0以降をお試しください。
